---
title: "Maps"
author: "Renata Diaz"
date: "5/4/2019"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(dplyr)
library(viridis)
library(ggplot2)
library(here)
```

```{r handle data}

can <- read_sf(paste0(here(), '/data/can_census_divisions_shp/gcd_000b11a_e.shp'))

qu <- unique(can$PRNAME)[6]

can<- can %>%
  filter(PRNAME == qu) %>%
  mutate(CDUID = as.integer(CDUID))

data_files <- list.files(path = paste0(here::here(), '/data/citsci_metrics'), full.names = T)

for(i in 1:length(data_files)) {
  this_taxon = unlist(strsplit(data_files[i], split = "_"))[6]
  this_taxon = substr(this_taxon, 1, nchar(this_taxon) - 4)
  
  this_data <- read.csv(data_files[i], stringsAsFactors = F)
  
  this_can <- can %>%
    left_join(this_data, by = 'CDUID')
  
  # Make maps of summary stats from toy stats
  # Use viridis for color blind friendly colors.
  
  
  print(Sys.time())
  
  obspercap_plot <- ggplot(data = this_can) +
    geom_sf(aes(fill = obs_totalpop)) +
    scale_fill_viridis() +
    ggtitle(paste0('Observations per capita - ', this_taxon))
  
  print(obspercap_plot)
  print(Sys.time())
  
  indpercap_plot <- ggplot(data = this_can) +
    geom_sf(aes(fill = observer_totalpop)) +
    scale_fill_viridis() +
    ggtitle(paste0('Observers per capita - ', this_taxon))
  
  print(indpercap_plot)
  print(Sys.time())
  
  obsperind_plot <-  ggplot(data = this_can) +
    geom_sf(aes(fill = mean_obs_per_observer)) +
    scale_fill_viridis() +
    ggtitle(paste0('Observations per observer - ', this_taxon))
  
  print(obsperind_plot)
  print(Sys.time())
}

```
