---
title: "Maps"
author: "Renata Diaz"
date: "5/4/2019"
output:
  github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sf)
library(dplyr)
library(viridis)
library(ggplot2)
library(here)
```

```{r handle data}

can <- read_sf(paste0(here(), '/data/can_census_divisions_shp/gcd_000b11a_e.shp'))

qu <- unique(can$PRNAME)[6]

can<- can %>%
  filter(PRNAME == qu) %>%
  mutate(CDUID = as.integer(CDUID))

bird_data <- read.csv(paste0(here(), '/data/citsci_metrics/citsci_metrics_birds.csv'), stringsAsFactors = F)

can <- can %>%
  left_join(bird_data, by = 'CDUID')

```

```{r make birds maps}

# Make maps of summary stats from toy stats
# Use viridis for color blind friendly colors.

can_short <- can[1:10, ]

print(Sys.time())

obspercap_plot <- ggplot(data = can) +
  geom_sf(aes(fill = obs_totalpop)) +
  scale_fill_viridis() +
  ggtitle('Observations per capita - Birds')

print(obspercap_plot)
print(Sys.time())

indpercap_plot <- ggplot(data = can) +
  geom_sf(aes(fill = observer_totalpop)) +
  scale_fill_viridis() +
  ggtitle('Observers per capita - Birds')

print(indpercap_plot)
print(Sys.time())

obsperind_plot <-  ggplot(data = can) +
  geom_sf(aes(fill = mean_obs_per_observer)) +
  scale_fill_viridis() +
  ggtitle('Observations per observer - Birds')

print(obsperind_plot)
print(Sys.time())

```
